version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    volumes: 
      - zoodata:/var/lib/zookeeper/data
      - zoolog:/var/lib/zookeeper/log

  kafka:
    image: nashtech/kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:32181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes: 
      - kafkadata:/var/lib/kafka/data

  postgres-source-1:
    image: postgres
    container_name: postgres-source-1
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres-source-2:
    image: postgres
    container_name: postgres-source-2
    hostname: postgres-source-2
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata2:/var/lib/postgresql/data
	  
  postgres-sink:
    image: postgres
    container_name: postgres-sink
    hostname: postgres-sink-hostname
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_sink:/var/lib/postgresql/data

volumes:
  zoodata:
  zoolog:
  kafkadata:
  pgdata:
  pgdata2:
  pgdata_sink: